apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appLabel }}
    component: html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello, Kubernetes!</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
    </body>
    </html>
