apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabel }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 80
        volumeMounts:
        - name: nginx-index-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-volume
        configMap:
          name: nginx-index
