apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabel }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
